name: tests

on: [push]

jobs:
    run:
        strategy:
            matrix:
                include:
                    - php-versions: '7.2'
                      phpunit-versions: '8.5.20'
                      operating-system: 'ubuntu-latest'
                    - php-versions: '7.3'
                      phpunit-versions: 'latest'
                      operating-system: 'ubuntu-latest'
                    - php-versions: '7.4'
                      phpunit-versions: 'latest'
                      operating-system: 'ubuntu-latest'
                    - php-versions: '8.0'
                      phpunit-versions: 'latest'
                      operating-system: 'ubuntu-latest'
                    - php-versions: '8.1'
                      phpunit-versions: 'latest'
                      operating-system: 'ubuntu-latest'
        runs-on: ${{ matrix.operating-system }}
        name: PHP ${{ matrix.php-versions }} test on ${{ matrix.operating-system }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP ${{ matrix.php-versions }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  coverage: none
                  tools: phpunit:${{ matrix.phpunit-versions }}

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Run test suite
              run: phpunit
