name: tests

on: [push]

jobs:
    run:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ['7.2', '7.3', '7.4', '8.0']
        name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP 7.x
              if: ${{ matrix.php-versions != '8.0' }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  coverage: none
                  tools: phpunit:8.5.8

            - name: Setup PHP 8.x
              if: ${{ matrix.php-versions == '8.0' }}
              uses: shivammathur/setup-php@v2
              with:
                   php-version: ${{ matrix.php-versions }}
                   coverage: none
                   tools: phpunit

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Run test suite
              run: phpunit
